server:
  port: ${PORT:8065}
message: Configuracion de Producto en el servidor levantado!
spring: 
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 12345678
    url: jdbc:mysql://localhost:3306/crudcloud?serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQLDialect
  cloud:
    config:
      uri: http://localhost:8080
eureka:
  client:
    register-with-eureka: true
    serviceurl:
      defaultZone: http://localhost:8761/eureka/
